"""EXP-003 FineWeb-Edu preparation with frozen EXP-001/002 controls."""

from __future__ import annotations

import itertools
import shutil
import time
from pathlib import Path
from typing import Any, Iterable, Iterator

import torch

from .data import (
    Document,
    _stream_token_ids,
    assign_split,
    build_benchmark_filter,
    iter_fineweb_documents,
    make_packed_examples,
    resolve_fineweb_revision,
    stable_document_id,
    tensor_sha256,
    write_token_stream,
)
from .utils import atomic_json_write, sha256_file

FROZEN_TOKENIZER_SHA256 = "c5592fba176c3d2f7915a3812559a24d7a669206f4a22484b053c8a9ce08be14"
GENERAL_VALIDATION_INPUTS_SHA256 = "f721fda2a0a0ca11a580178dba6c2592af4dd9324da3ed7120624b7364d653f7"
GENERAL_VALIDATION_TARGETS_SHA256 = "2ca518affa0b36d15c7c427de84b4c7d761926e1e993c03724d75f396934f13e"
EDU_VALIDATION_PREDICTION_TOKENS = 131_072
FINEWEB_EDU_LICENSE = "ODC-BY"
FINEWEB_EDU_PROVENANCE = (
    "Filtered public FineWeb content; the FineWeb-Edu educational classifier was trained using annotations "
    "generated by Llama-3-70B-Instruct. The training text itself is not synthetic."
)


def scaling_milestones(config: Any) -> tuple[int, int, int, int]:
    """The predeclared two-validation learning-curve checkpoints."""
    if config.experiment_id != "EXP-003" or config.training.full_schedule_steps != 9156:
        raise ValueError("EXP-003 milestones require the fixed 9,156-step horizon.")
    return (0, 3052, 6104, 9156)


def assert_frozen_exp003_artifacts(tokenizer_path: Path, validation_path: Path) -> None:
    """Reject a retrained tokenizer or changed general-language validation control."""
    if sha256_file(tokenizer_path) != FROZEN_TOKENIZER_SHA256:
        raise RuntimeError("EXP-003 requires the exact frozen EXP-001 tokenizer artifact.")
    values = torch.load(validation_path, map_location="cpu", weights_only=True)
    if tensor_sha256(values["inputs"]) != GENERAL_VALIDATION_INPUTS_SHA256 or tensor_sha256(
        values["targets"]
    ) != GENERAL_VALIDATION_TARGETS_SHA256:
        raise RuntimeError("EXP-003 requires the exact frozen EXP-001/002 general validation artifact.")


def _validation_record(path: Path, inputs: torch.Tensor, targets: torch.Tensor, documents_used: int) -> dict[str, Any]:
    return {
        "file": path.name,
        "prediction_tokens": int(targets.numel()),
        "examples": int(inputs.shape[0]),
        "documents_used": documents_used,
        "inputs_sha256": tensor_sha256(inputs),
        "targets_sha256": tensor_sha256(targets),
    }


def _eligible_documents(
    config: Any,
    source: Iterator[str],
    contamination_filter: Any,
    tokenizer: Any,
    eod_id: int,
) -> tuple[list[Document], list[Document], dict[str, int], Iterator[str]]:
    """Read one deterministic prefix until the held-out edu validation has enough tokens."""
    initial_train: list[Document] = []
    validation_documents: list[Document] = []
    counters = {"scanned": 0, "accepted": 0, "rejected": 0, "edu_validation_tokens_before_trim": 0}
    required_stored = EDU_VALIDATION_PREDICTION_TOKENS + 1
    for text in source:
        counters["scanned"] += 1
        document_id = stable_document_id(text)
        split = assign_split(
            document_id,
            config.data.split_seed,
            config.data.validation_bucket_modulus,
            config.data.validation_bucket_cutoff,
        )
        if contamination_filter.screen(text).rejected:
            counters["rejected"] += 1
            continue
        counters["accepted"] += 1
        document = Document(document_id, text, split)
        if split == "train":
            initial_train.append(document)
        else:
            validation_documents.append(document)
            counters["edu_validation_tokens_before_trim"] += len(tokenizer.encode(text).ids) + 1
            if counters["edu_validation_tokens_before_trim"] >= required_stored:
                return initial_train, validation_documents, counters, source
    raise RuntimeError("FineWeb-Edu stream ended before creating the required held-out educational validation set.")


def prepare_exp003(
    config: Any,
    artifact_dir: Path,
    exp001_artifact_dir: Path,
    *,
    validation_only: bool = False,
) -> dict[str, Any]:
    """Prepare the no-cycle EXP-003 stream, or only its edu validation for baseline measurement.

    The source is always streamed from its pinned revision from the beginning.
    It neither retrains a tokenizer nor reuses an EXP-002 token stream.
    """
    from .tokenizer import load_tokenizer

    if config.experiment_id != "EXP-003":
        raise ValueError("prepare_exp003 requires configs/exp003.yaml.")
    started = time.perf_counter()
    source_artifact = Path(exp001_artifact_dir)
    frozen_tokenizer = source_artifact / "tokenizer" / "tokenizer.json"
    frozen_validation = source_artifact / "validation.pt"
    assert_frozen_exp003_artifacts(frozen_tokenizer, frozen_validation)

    artifact_dir = Path(artifact_dir)
    artifact_dir.mkdir(parents=True, exist_ok=True)
    (artifact_dir / "tokenizer").mkdir(exist_ok=True)
    copied_tokenizer = artifact_dir / "tokenizer" / "tokenizer.json"
    shutil.copy2(frozen_tokenizer, copied_tokenizer)
    general_validation_path = artifact_dir / "general_validation.pt"
    shutil.copy2(frozen_validation, general_validation_path)
    tokenizer = load_tokenizer(frozen_tokenizer)
    eod_id = tokenizer.token_to_id(config.data.eod_token)
    if eod_id is None:
        raise RuntimeError("Frozen EXP-001 tokenizer has no EOD token.")

    cache_dir = artifact_dir / "cache"
    revision = resolve_fineweb_revision(config.data)
    contamination_filter, benchmark_sources = build_benchmark_filter(
        cache_dir / "benchmarks", config.data.contamination_ngram_size
    )
    source_documents = iter(iter_fineweb_documents(config.data, revision, cache_dir / "fineweb-edu"))
    initial_train, validation_documents, counters, source_documents = _eligible_documents(
        config, source_documents, contamination_filter, tokenizer, eod_id
    )
    edu_stream, edu_documents_used = _stream_token_ids(
        tokenizer, validation_documents, eod_id, EDU_VALIDATION_PREDICTION_TOKENS
    )
    edu_inputs, edu_targets = make_packed_examples(edu_stream, config.data.context_length)
    if int(edu_targets.numel()) != EDU_VALIDATION_PREDICTION_TOKENS:
        raise RuntimeError("EXP-003 educational validation does not contain exactly 131,072 prediction tokens.")
    edu_validation_path = artifact_dir / "edu_validation.pt"
    torch.save({"inputs": edu_inputs, "targets": edu_targets}, edu_validation_path)
    general_values = torch.load(general_validation_path, map_location="cpu", weights_only=True)

    manifest: dict[str, Any] = {
        "experiment_id": "EXP-003",
        "dataset": {
            "repo": config.data.dataset_repo,
            "config": config.data.dataset_config,
            "revision": revision,
            "field": config.data.text_field,
            "license": FINEWEB_EDU_LICENSE,
            "provenance": FINEWEB_EDU_PROVENANCE,
        },
        "training_source": "FineWeb-Edu accepted train documents only; no synthetic teacher completions.",
        "split": {
            "method": "sha256(seed:canonical_content_sha256) modulo buckets",
            "seed": config.data.split_seed,
            "validation_buckets": config.data.validation_bucket_cutoff,
            "modulus": config.data.validation_bucket_modulus,
        },
        "contamination": {
            "method": "NFKC+casefold+tokenized normalized 13-gram SHA-256 overlap",
            "ngram_size": config.data.contamination_ngram_size,
            "benchmark_sources": benchmark_sources,
            "scanned_documents": counters["scanned"],
            "accepted_documents": counters["accepted"],
            "rejected_documents": counters["rejected"],
        },
        "tokenizer": {
            "path": "tokenizer/tokenizer.json",
            "sha256": sha256_file(copied_tokenizer),
            "vocab_size": 8192,
            "special_tokens": [config.data.eod_token],
            "frozen_from": str(frozen_tokenizer),
        },
        "general_validation": _validation_record(
            general_validation_path, general_values["inputs"], general_values["targets"], 0
        ),
        "edu_validation": {
            **_validation_record(edu_validation_path, edu_inputs, edu_targets, edu_documents_used),
            "split": {
                "method": "sha256(seed:canonical_content_sha256) modulo buckets",
                "seed": config.data.split_seed,
                "validation_buckets": config.data.validation_bucket_cutoff,
                "modulus": config.data.validation_bucket_modulus,
            },
            "contamination_screened": True,
        },
        "preparation_mode": "validation_only" if validation_only else "full_stream",
    }
    if validation_only:
        manifest["preparation_wall_seconds"] = time.perf_counter() - started
        atomic_json_write(artifact_dir / "manifest.json", manifest)
        return manifest

    documents_contributed = 0

    def train_token_ids() -> Iterator[int]:
        nonlocal documents_contributed
        for document in initial_train:
            documents_contributed += 1
            yield from tokenizer.encode(document.text).ids
            yield eod_id
        for text in source_documents:
            counters["scanned"] += 1
            document_id = stable_document_id(text)
            split = assign_split(
                document_id,
                config.data.split_seed,
                config.data.validation_bucket_modulus,
                config.data.validation_bucket_cutoff,
            )
            if contamination_filter.screen(text).rejected:
                counters["rejected"] += 1
                continue
            counters["accepted"] += 1
            if split == "train":
                documents_contributed += 1
                yield from tokenizer.encode(text).ids
                yield eod_id

    stored_tokens = config.training.full_training_tokens + 1
    stream_path = artifact_dir / "train-token-stream.uint16"
    stream = write_token_stream(
        stream_path,
        itertools.islice(train_token_ids(), stored_tokens),
        stored_tokens,
        config.data.context_length,
    )
    manifest["contamination"].update(
        {
            "scanned_documents": counters["scanned"],
            "accepted_documents": counters["accepted"],
            "rejected_documents": counters["rejected"],
        }
    )
    manifest["packed"] = {
        "representation": "one-dimensional uint16 token stream with on-demand torch.long 513-token views",
        "storage_dtype": "uint16",
        "context_length": config.data.context_length,
        "prediction_tokens_per_example": config.training.sequence_predictions,
        "train_prediction_tokens": config.training.full_training_tokens,
        "train_token_count_including_final_target": stored_tokens,
        "train_examples": len(stream),
        "train_stream_file": stream_path.name,
        "train_stream_bytes": stream_path.stat().st_size,
        "train_stream_sha256": sha256_file(stream_path),
        "train_documents_contributed": documents_contributed,
        "non_cycled": True,
    }
    manifest["preparation_wall_seconds"] = time.perf_counter() - started
    atomic_json_write(artifact_dir / "manifest.json", manifest)
    return manifest
